const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94761643978"
const SESSION_ID = "PRABATH-MD~F38jFCwI#o34Ccl3WLys9aEeFDllMgILjGijTC3i8SKjSv85Okyg"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
